apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking
spec:
  replicas: 1
  selector:
matchLabels:
      app: banking
  template:
    metadata:
      labels:
        app: banking
    spec:
      containers:
      - name: banking
        image: chandanyadavks/banking:latest
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: banking
spec:
  type: NodePort
  selector:
    app: banking  #<-- must match Deployment label
  ports:
  - port: 8081
targetPort: 8081
nodePort: 30090 # Optional: specify NodePort (default random 30000–32767)
